services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: jenkins
      POSTGRES_PASSWORD: jenkins
      POSTGRES_DB: jenkins_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: